services:
  backend:
    # Build from source only if BACKEND_TARGET is set to a build target
    build:
      context: ./
      dockerfile: Dockerfile
      target: "${BACKEND_TARGET:-live-dev}"  # defaults to live-dev
    # Pull/run prebuilt image if BACKEND_TARGET is 'image' or not set
    image: "${BACKEND_IMAGE:-binary141/avenue:latest}"

    volumes:
      - ./:/app:rw
      - upload-data:/avenue/uploads
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      MAX_FILE_BYTE_SIZE: 1073741824
      UPLOAD_DIR: "/avenue/uploads"
      REGISTRATION_ENABLED: "true"
      APP_ENV: "dev"
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: secret
      DB_DATABASE: avenue

  postgres:
    image: postgres:16.3
    volumes:
      - ./db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: avenue
    ports:
      - "5432:5432"

volumes:
  upload-data:
  db-data:

