services:
  backend:
    build:
      target: "${BACKEND_TARGET:-live-dev}"
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app:rw 
      - upload-data:/avenue/uploads
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      MAX_FILE_BYTE_SIZE: 1073741824
      UPLOAD_DIR: "/avenue/uploads"
      APP_ENV: "production"
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: secret
      DB_DATABASE: avenue

  postgres:
    image: postgres:16.3
    volumes:
      - ./db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: avenue
    ports:
      - "5432:5432"
   
volumes:
  upload-data:
  db-data:
